// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfVtZNwgUlCU3aEgmq9jGG-oa8MHDNhec',
    appId: '1:877165690134:web:9c1e8ad907811ce86d2437',
    messagingSenderId: '877165690134',
    projectId: 'organblooddonation-595e6',
    authDomain: 'organblooddonation-595e6.firebaseapp.com',
    storageBucket: 'organblooddonation-595e6.firebasestorage.app',
    measurementId: 'G-M33XGSCM85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwTGLhFJlUnQGBhQSj6CQLW6RHYVtXQKU',
    appId: '1:877165690134:android:0cf891edae766e646d2437',
    messagingSenderId: '877165690134',
    projectId: 'organblooddonation-595e6',
    storageBucket: 'organblooddonation-595e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe9grlc7xtNNmo1u446HjCfRH5CRaA31Q',
    appId: '1:877165690134:ios:943c8228a9cf41cc6d2437',
    messagingSenderId: '877165690134',
    projectId: 'organblooddonation-595e6',
    storageBucket: 'organblooddonation-595e6.firebasestorage.app',
    iosBundleId: 'com.example.organBloodDonationManagement',
  );
}
